---
title: "Test fairness"
output: html_notebook
---

```{r}
library(tidyverse)
library(magrittr)
library(caret)
library(fairml)
library(gbm)
library(fastDummies)
library(grf)
# detach("wakefield")
```

```{r}
# Set global variables
set.seed(11111111)
test_size <- 5000

ntree <- 500
```

```{r}
# Import and wrangle data
data("law.school.admissions")
data <- law.school.admissions
data %<>% dummy_cols() %>% janitor::clean_names() %>% select(age:race1_white) %>% select(-gender, -race1) %>% mutate_if(is.factor, as.integer)
```

```{r}
# Create data for training
smp_size <- floor(0.75 * nrow(data))
train_ind <- sample(seq_len(nrow(data)), size = smp_size)

train <- data[train_ind, ]
test <- data[-train_ind, ]
test_orig <- law.school.admissions[-train_ind, c("gender", "race1")]
```


```{r}
# Fit nuisance model
data_folds <- createFolds(train$ugpa)

targets <- names(law.school.admissions)[!(names(law.school.admissions) %in% c('gender', 'race1'))]

for (i in 1:length(targets)) {
  data[paste0(targets, "_est")] <- NULL
  data[targets] <- as.numeric(data[targets] %>% pull)
}

  # Split sample
  
  covars <- select(train, gender_male, gender_female, race1_white, race1_black, race1_hisp, race1_asian, race1_other) %>% as.matrix.data.frame()
  
  # Fit models
  nuisance_models <- map(targets, function (x) {
    Y <- select(train, x) %>% pull()
    
    regression_forest(X=covars, Y=Y, num.trees = ntree)
    })
  names(nuisance_models) <- targets
  
  # Get estimates
for (variable in 1:length(targets)) {
  train[,paste0(targets[variable], '_res')] <- train[,targets[variable]] - predict(nuisance_models[[variable]], data = train)$predictions
}
      
```

```{r}
# Fit final models
final_model <- regression_forest(Y=train$ugpa_res, X= train %>% select(ends_with("_res"), -ugpa_res), num.trees = ntree)

final_model_unfair <- regression_forest(Y=train$ugpa, X= select(train, age, decile1, decile3, fam_inc, lsat, ugpa, cluster, fulltime), num.trees = ntree)
```

```{r}
# Get nuisance predictions for test sample
## Make function to get predictions from ensemble of nuisance models
predict_cross <- function(models, data = test) {
  preds <- map(models, ~predict(.x, data) %>% .$predictions)

  names(preds) <- paste0('model', 1:length(models))
  bind_cols(preds) %>% rowMeans()
}

dml_fair <- function(data) {
  
  ## Get nuisance estimates
      predict_data <- select(data, gender_male, gender_female, race1_white, race1_black, race1_hisp, race1_asian, race1_other) %>% 
    as.matrix.data.frame()
  
resids <- map(targets, function (x) {
    pred <- predict(nuisance_models[[x]], predict_data)
    resid <- data[x] - pred
})

# tars <- targets

resids %<>% as.data.frame()
names(resids) <- paste0(targets, '_res')
  
  # Get predictions
  final_prediction_model <- final_model %>% predict(resids %>% select(-ugpa_res))
  final_predictions <- final_prediction_model$predictions
  
  final_prediction_model_unfair <- final_model_unfair %>% predict(data %>% select(all_of(targets), -ugpa))
  final_predictions_unfair <- final_prediction_model_unfair$predictions
  
  data$ests <- final_predictions
  data$ests_unfair <- final_predictions_unfair
  
  data
}


```


```{r}
# Base case
base_case <- predict(nuisance_models$ugpa, data.frame(
  gender_male = 1,
  gender_female = 0,
  race1_white = 1,
  race1_black = 0,
  race1_hisp = 0,
  race1_asian = 0, 
  race1_other = 0
  )
        )
```

```{r}
# Get DML adjustments
test <- dml_fair(test)
```

```{r}
# Create residuals + base case predictions
test$bcY <- test$ests + base_case %>% pull()

# Add original gender and race in for visualisations
test <- 

# Gather in long format
data_long <- bind_cols(test, test_orig %>%
  select(gender, race1)) %>%
  gather(key = "estimate", value = "value", bcY, ests_unfair) %>%
  mutate(estimate = ifelse(estimate == "bcY", "DML Fairness", "Unawareness"))
```



```{r}
make_facets <- function(data, variable, facet_var = NULL) {
  variable <- ensym(variable)
  
  if(is.null(facet_var)) {
    facet_setting <- facet_grid(cols = vars(estimate))
  } else {
    facet_setting <- facet_grid(cols = vars(estimate), rows = vars(!!variable))
  }
  
  data %>%
    ggplot(aes(x = !!variable, y = value)) +
    geom_violin() +
    stat_summary(fun.data = "mean_cl_boot",
               geom = "crossbar", 
               width = 0.5,
               colour = "red") +
    facet_grid(cols = vars(estimate))
}
```

```{r}
# Gender graph
make_facets(data_long, gender)
ggsave("gender_lsac.png", width = 7, height = 7)
```

```{r}
# Race graph
make_facets(data_long, race1)
ggsave("race_lsac.png", width = 10, height = 7)
```

```{r}
# Race graph
make_facets(data_long, race1) +
  facet_grid(cols = vars(estimate), rows = vars(gender))

ggsave("racegender_lsac.png", width = 10, height = 7)
```





